### ISSUE TITLE
No animation when interval is too low

### ISSUE THREAD

**Issue by ndvbd** [tomik23/circular-progress-bar#16]
This doesn't work, 
  ```
 var circle = new CircularProgressBar('someclass');

        setTimeout(() => {
          circle.animationTo({
            index: 0,
            percent: Math.floor(75)
          });
        }, 10);
```

while this works:

```
   var circle = new CircularProgressBar('someclass');

        setTimeout(() => {
          circle.animationTo({
            index: 0,
            percent: Math.floor(75)
          });
        }, 30);
```

There is some issue with the timing

**Comment by ndvbd** [comment]
I assume it's because the initial animation didn't finish

**Comment by tomik23** [comment]
Yes, on the other hand why run the next animation after 1/1000s?

**Comment by ndvbd** [comment]
sometimes you dont control it, you get a response from server with progress and you just update using animateTo....

**Comment by tomik23** [comment]
Yes, I understand that there is such data, but a pie chart, especially its animation, is a rather bad choice if we have to do an animation every 1/10s :)
