### ISSUE TITLE
How to disable the text mechanism and leave only the moving circle?

### ISSUE THREAD

**Issue by ndvbd** [tomik23/circular-progress-bar#17]
How to disable the text mechanism and leave only the moving circle?

**Comment by tomik23** [comment]
I recommend reading the documentation - [configuration-of-the-plugin](https://github.com/tomik23/circular-progress-bar#configuration-of-the-plugin)

**Comment by ndvbd** [comment]
Thanks:

"number": false

**Comment by tomik23** [comment]
Yes, that's right 👍
