### ISSUE TITLE
Polyfill loading throws error in Internet Explorer 11

### ISSUE THREAD

**Issue by ndvbd** [tomik23/circular-progress-bar#28]
Polyfill loading throws error in Internet Explorer 11:

![image](https://user-images.githubusercontent.com/845175/119936976-adfb7380-bf92-11eb-94c9-60bc4a298a70.png)

**Comment by tomik23** [comment]
I tested on ie11 and ie10, it works, no error, everything works. Only the appearance breaks down a bit, but this has no effect on performance.
