### ISSUE TITLE
colorSlice not changing dynamically

### ISSUE THREAD

**Issue by AlonKapi** [tomik23/circular-progress-bar#43]
I'm not sure if it's intended or not but using for example:
```
setTimeout(() => {
            const options = {
                // item number you want to update
                "index": 1,
                // set a new percentage
                "percent": 30,
                // set a new color
                "colorSlice": "#000"
            };
            circle.animationTo(options);
}, 3000); // after 3s update
```

And the stroke isn't changing color to black.
This can be useful if for example for percentage < 30 then set font color and stroke color to green, if percentage < 60 then set colors to orange, etc..

**Comment by tomik23** [comment]
That's right, only the percentage update is working at the moment.
As for the color change, work is already underway to implement this solution ;)
