### ISSUE TITLE
Percentage of circle no longer changing after reaching 0%.

### ISSUE THREAD

**Issue by Philrobots** [tomik23/circular-progress-bar#83]
Hello,

We use your Circle in our application and we often change the percent options with the  `animationTo` function.

The problem we encounter is that when we make a change with a percentage of 0%, then the circle changes for a percentage of 0% but it then stays at 0% no matter what changes we make afterwards.

For example, if we decide to change the circle to 40%, it will change to 40%.

If we ask it to change to 0%, it changes to 0%,

But if we ask it again to change to 95%, it stays at 0%.

There must be a condition in the code, such as 

`if (percent) { ...`

and it does not enters the condition since `if(0) ` does not enter the condition in Javascript 

<img width="222" alt="image" src="https://github.com/tomickigrzegorz/circular-progress-bar/assets/47373969/35fe0f72-ae42-4870-8b76-1e1884e831a0">

**Comment by tomickigrzegorz** [comment]
I checked the operation and everything seems to be working properly.
I made a new build so you can use it now.
